/**
 * Árvore de pesquisa da Era 1 (GDD §3, §7, §8.6, v0.6). Só dados.
 *
 * 🔬 deixou de ser limiar e virou **moeda**: cada nó é uma decisão, e cada nó traz uma frase de física
 * de verdade (`fisica`) — é o card de uma linha que o §9 pede. As três melhorias nomeadas das sessões
 * anteriores (Lâminas de fibra, Rastreamento solar, Grade 7×7) viraram nós daqui, e os desbloqueios de
 * usina (turbina eólica, bateria) passaram a **gastar** 🔬 em vez de só exigir.
 */
import type { NoDef, RamoDef } from "./arvore-tipos";

export type { EfeitoNo, NoDef, RamoDef, RamoId } from "./arvore-tipos";

export const RAMOS_ERA1: readonly RamoDef[] = [
  { id: "vento", era: 1, nome: "Vento", descricao: "Pás, torres e a esteira que uma turbina deixa atrás de si." },
  { id: "sol", era: 1, nome: "Sol", descricao: "Luz que vira corrente — e luz que vira calor na Torre." },
  { id: "rede", era: 1, nome: "Rede", descricao: "Levar a energia mais longe e guardá-la para depois." },
  { id: "nucleo", era: 1, nome: "Núcleo", descricao: "As cinco peças da Torre Solar, uma geração acima." },
  { id: "cidade", era: 1, nome: "Cidade", descricao: "O que a cidade faz com cada kW que recebe." },
];

/**
 * A ordem dentro de cada ramo é a ordem da coluna na tela da árvore.
 * Os números vêm de §8.6 e foram recalibrados pela simulação de 60 minutos (parte F da Sessão 7).
 */
export const NOS_ERA1: readonly NoDef[] = [
  /* ---------------------------------------------------------------- Vento */
  {
    id: "laminasDeFibra",
    ramo: "vento",
    era: 1,
    nome: "Lâminas de fibra",
    efeitoTexto: "Cata-vento e turbina eólica +25 %.",
    fisica: "Fibra de vidro pesa um terço do aço para a mesma rigidez, então a pá pode ser mais longa — e a potência cresce com a área varrida, que vai com o quadrado do comprimento.",
    pesquisa: 25,
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["cataVento", "turbinaEolica"], fator: 1.25 }],
  },
  {
    id: "turbinaEolica",
    ramo: "vento",
    era: 1,
    nome: "Turbina eólica",
    efeitoTexto: "Libera a turbina eólica (6 kW) na paleta.",
    fisica: "Uma torre de 30 m alcança um vento mais rápido e menos turbulento que o do quintal: a camada-limite do ar freia tudo o que está perto do chão.",
    pesquisa: 40,
    efeitos: [{ tipo: "desbloqueia", construcao: "turbinaEolica" }],
  },
  {
    id: "torreMaisAlta",
    ramo: "vento",
    era: 1,
    nome: "Torre mais alta",
    efeitoTexto: "Cata-vento e turbina eólica +40 %.",
    fisica: "A potência do vento vai com o cubo da velocidade, e a 80 m o vento é uns 30 % mais rápido que a 30 m. No papel isso seria mais que o dobro; a torre mais alta e mais pesada come o resto, e sobra +40 %.",
    pesquisa: 150,
    pre: ["laminasDeFibra"],
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["cataVento", "turbinaEolica"], fator: 1.4 }],
  },
  {
    id: "controleDePasso",
    ramo: "vento",
    era: 1,
    nome: "Controle de passo",
    efeitoTexto: "A esteira entre vizinhos eólicos cai pela metade (−20 % → −10 %).",
    fisica: "Girar a pá em torno do próprio eixo muda o ângulo de ataque e, com ele, o quanto de vento a turbina rouba de quem está atrás. Parques reais fazem isso de propósito.",
    pesquisa: 1_000,
    pre: ["torreMaisAlta"],
    efeitos: [{ tipo: "esteira", fator: 0.5 }],
  },
  {
    id: "rotorTresPas",
    ramo: "vento",
    era: 1,
    nome: "Rotor de três pás",
    efeitoTexto: "Cata-vento e turbina eólica +15 %.",
    fisica: "Três pás é o meio-termo que venceu: duas vibram a cada passagem pela torre, quatro custam mais do que acrescentam, porque o ar que passa já foi desacelerado pela pá anterior.",
    pesquisa: 2_000,
    pre: ["controleDePasso"],
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["cataVento", "turbinaEolica"], fator: 1.15 }],
  },
  {
    id: "eixoVertical",
    ramo: "vento",
    era: 1,
    nome: "Eixo vertical",
    efeitoTexto: "Acaba com a esteira — e tira 20 % da potência eólica.",
    fisica: "Um rotor vertical (Darrieus) não precisa se virar para o vento e deixa uma esteira que se recompõe rápido, mas a pá passa metade da volta trabalhando contra o vento: rende menos por área.",
    pesquisa: 4_000,
    pre: ["rotorTresPas"],
    exclui: ["eixoHorizontal"],
    efeitos: [
      { tipo: "esteira", fator: 0 },
      { tipo: "potenciaUsinas", usinas: ["cataVento", "turbinaEolica"], fator: 0.8 },
    ],
  },
  {
    id: "eixoHorizontal",
    ramo: "vento",
    era: 1,
    nome: "Eixo horizontal",
    efeitoTexto: "Mantém a esteira e ganha mais 20 % de potência eólica.",
    fisica: "O rotor horizontal encara o vento o tempo todo e chega perto do limite de Betz (59 % da energia do vento). O preço é a esteira: quem fica atrás recebe um vento já gasto.",
    pesquisa: 4_000,
    pre: ["rotorTresPas"],
    exclui: ["eixoVertical"],
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["cataVento", "turbinaEolica"], fator: 1.2 }],
  },

  /* ------------------------------------------------------------------ Sol */
  {
    id: "painelBifacial",
    ramo: "sol",
    era: 1,
    nome: "Painel bifacial",
    efeitoTexto: "Painel solar +15 %.",
    fisica: "O painel bifacial também gera com a luz que o chão devolve. Sobre areia clara o albedo passa de 0,3: quase um terço da luz volta para cima.",
    pesquisa: 60,
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["painelSolar"], fator: 1.15 }],
  },
  {
    id: "antirreflexo",
    ramo: "sol",
    era: 1,
    nome: "Antirreflexo",
    efeitoTexto: "Painel solar +8 %.",
    fisica: "Uma camada de espessura igual a um quarto do comprimento de onda faz a luz refletida na frente e no fundo dela se cancelar por interferência. O vidro nu devolve uns 8 % da luz; com a camada, quase nada.",
    pesquisa: 200,
    pre: ["painelBifacial"],
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["painelSolar"], fator: 1.08 }],
  },
  {
    id: "limpezaAutomatica",
    ramo: "sol",
    era: 1,
    nome: "Limpeza automática",
    efeitoTexto: "Painel solar +10 %.",
    fisica: "Poeira acumulada tira de 10 % a 25 % da geração num clima seco. É a manutenção mais barata que existe: passar uma escova.",
    pesquisa: 1_300,
    pre: ["antirreflexo"],
    efeitos: [{ tipo: "potenciaUsinas", usinas: ["painelSolar"], fator: 1.1 }],
  },
  {
    id: "rastreamentoSolar",
    ramo: "sol",
    era: 1,
    nome: "Rastreamento solar",
    efeitoTexto: "Cada espelho do Núcleo injeta 5 u/s em vez de 4. Muda o equilíbrio — reajuste a grade.",
    fisica: "Um espelho fixo só aponta certo duas vezes por dia; seguindo o Sol em dois eixos ele mantém o feixe no receptor o dia inteiro. É por isso que toda torre solar de verdade tem heliostatos móveis.",
    pesquisa: 30,
    creditos: 150,
    efeitos: [{ tipo: "calorPorEspelho", valor: 5 }],
  },

  /* ----------------------------------------------------------------- Rede */
  {
    id: "bateria",
    ramo: "rede",
    era: 1,
    nome: "Bateria",
    efeitoTexto: "Libera a bateria (+20 kWh, ±10 kW) na paleta.",
    fisica: "Guardar energia é o que separa uma rede que oscila de uma rede que aguenta: a bateria cobre o buraco de segundos entre o que a cidade pede e o que o vento dá.",
    pesquisa: 20,
    efeitos: [{ tipo: "desbloqueia", construcao: "bateria" }],
  },
  {
    id: "laboratorio",
    ramo: "rede",
    era: 1,
    nome: "Laboratório",
    efeitoTexto: "Libera o laboratório (🔬 0,2/s, consome 2 kW) na paleta.",
    fisica: "Ciência custa energia: um laboratório é um prédio que transforma kW em conhecimento — devagar, e sem parar.",
    pesquisa: 0,
    creditos: 0,
    efeitos: [{ tipo: "desbloqueia", construcao: "laboratorio" }],
  },
  {
    id: "subestacaoAltaTensao",
    ramo: "rede",
    era: 1,
    nome: "Subestação de alta tensão",
    efeitoTexto: "Alcance da subestação passa de 3 para 5 casas.",
    fisica: "A perda numa linha é R·I². Dobrando a tensão, a mesma potência viaja com metade da corrente e perde quatro vezes menos — por isso a linha longa é sempre de alta tensão.",
    pesquisa: 800,
    efeitos: [{ tipo: "alcanceSubestacao", casas: 5 }],
  },
  {
    id: "bateriaDeFluxo",
    ramo: "rede",
    era: 1,
    nome: "Bateria de fluxo",
    efeitoTexto: "Cada bateria guarda +50 % de kWh.",
    fisica: "Numa bateria de fluxo a energia está no eletrólito dos tanques e a potência está na célula onde ele passa: dá para aumentar só a capacidade, aumentando o tanque.",
    pesquisa: 1_600,
    pre: ["bateria", "subestacaoAltaTensao"],
    efeitos: [{ tipo: "capacidadeBateria", fator: 1.5 }],
  },
  {
    id: "universidade",
    ramo: "rede",
    era: 1,
    nome: "Universidade",
    efeitoTexto: "Libera a universidade: 🔬 pela raiz da população, 1 por 2 000 habitantes.",
    fisica: "Pesquisa escala com gente, mas não linearmente: dobrar a população não dobra as descobertas — por isso a raiz quadrada, e não a multiplicação.",
    pesquisa: 250,
    efeitos: [{ tipo: "desbloqueia", construcao: "universidade" }],
  },

  /* --------------------------------------------------------------- Núcleo */
  {
    id: "receptorCeramico",
    ramo: "nucleo",
    era: 1,
    nome: "Receptor cerâmico",
    efeitoTexto: "Receptor +50 u de capacidade.",
    fisica: "Cerâmicas de carbeto de silício aguentam mais de 1 000 °C sem fluência, onde o aço já amoleceu. Mais temperatura no receptor é mais margem antes do limite.",
    pesquisa: 80,
    creditos: 300,
    efeitos: [{ tipo: "receptorCeramico" }],
  },
  {
    id: "heliostatoDoisEixos",
    ramo: "nucleo",
    era: 1,
    nome: "Heliostato de dois eixos",
    efeitoTexto: "Todos os espelhos entregam +25 % de calor.",
    fisica: "Com dois eixos o espelho corrige azimute e elevação e mantém o ângulo de incidência pequeno o ano inteiro — o cosseno do erro é o que se perde.",
    pesquisa: 700,
    pre: ["rastreamentoSolar"],
    efeitos: [{ tipo: "calorEspelhoFator", fator: 1.25 }],
  },
  {
    id: "turbinaAltaPressao",
    ramo: "nucleo",
    era: 1,
    nome: "Turbina de alta pressão",
    efeitoTexto: "Cada u consumida rende +30 % de kW.",
    fisica: "O rendimento de Carnot é 1 − T_fria ÷ T_quente: subindo a pressão sobe a temperatura do vapor, e mais trabalho sai do mesmo calor.",
    pesquisa: 1_200,
    efeitos: [{ tipo: "turbinaKwFator", fator: 1.3 }],
  },
  {
    id: "radiadorAtivo",
    ramo: "nucleo",
    era: 1,
    nome: "Radiador ativo",
    efeitoTexto: "Radiador dissipa 9 u/s em vez de 6, consumindo 1 kW do Núcleo.",
    fisica: "Convecção forçada tira muito mais calor que convecção natural: o ventilador gasta energia para não deixar o ar quente ficar grudado na aleta.",
    pesquisa: 900,
    efeitos: [{ tipo: "radiadorAtivo", dissipacao: 9, consomeKw: 1 }],
  },
  {
    id: "tanqueDoisSais",
    ramo: "nucleo",
    era: 1,
    nome: "Tanque de dois sais",
    efeitoTexto: "Cada tanque guarda +50 % de capacidade.",
    fisica: "Dois tanques, um frio e um quente, deixam o sal trabalhar numa faixa de temperatura maior — e a energia guardada é massa × calor específico × ΔT.",
    pesquisa: 1_100,
    efeitos: [{ tipo: "capacidadeTanque", fator: 1.5 }],
  },
  {
    id: "grade7x7",
    ramo: "nucleo",
    era: 1,
    nome: "Grade 7×7",
    efeitoTexto: "Abre o anel 3: 24 casas novas, só para espelhos, a 1 u/s cada. O 5×5 fica no centro.",
    fisica: "Num campo de heliostatos os espelhos de fora chegam mais inclinados e rendem menos por área — e é por isso que crescer para fora só compensa junto com mais capacidade de armazenar.",
    pesquisa: 1_500,
    creditos: 2_000,
    efeitos: [{ tipo: "gradeLado", lado: 7 }],
  },

  /* --------------------------------------------------------------- Cidade */
  {
    id: "iluminacaoEficiente",
    ramo: "cidade",
    era: 1,
    nome: "Iluminação eficiente",
    efeitoTexto: "Os bairros pedem 10 % menos e pagam o mesmo por kW.",
    fisica: "Um LED entrega quase dez vezes mais luz por watt que uma lâmpada incandescente, que na prática era um aquecedor que também brilhava.",
    pesquisa: 250,
    efeitos: [{ tipo: "demandaBairro", fator: 0.9 }],
  },
  {
    id: "bombasDeCalor",
    ramo: "cidade",
    era: 1,
    nome: "Bombas de calor",
    efeitoTexto: "Tarifa +10 %.",
    fisica: "Uma bomba de calor não gera calor: ela move o que já existe lá fora, e por isso entrega 3 a 4 kWh de aquecimento por kWh elétrico. Eletricidade que substitui combustível vale mais.",
    pesquisa: 1_800,
    pre: ["iluminacaoEficiente"],
    efeitos: [{ tipo: "tarifa", fator: 1.1 }],
  },

  /* ----------------------------------------------------------- Saída da era */
  {
    id: "fissaoBasica",
    ramo: "nucleo",
    era: 1,
    nome: "Fissão básica",
    efeitoTexto: "Abre a Era 2. Exige Estabilidade 100 % no Núcleo.",
    fisica: "Um núcleo de urânio-235 atingido por um nêutron lento se parte e solta mais nêutrons: se cada fissão provoca exatamente uma outra, a reação se sustenta sozinha — é o k = 1 de um reator.",
    pesquisa: 3_000,
    creditos: 50_000,
    pre: ["receptorCeramico", "turbinaAltaPressao"],
    efeitos: [],
  },
];


